/* Latest dashboard: screenshot-aligned demonstration, isolated from existing reports. */
(() => {
  const root = document.getElementById('dashboardLatestView');
  if (!root) return;
  const dot = (color) => `<i class="dl-dot" style="background:${color}"></i>`;
  const colors = ['#ff506b','#ffd647','#14c8ad','#9bb4ce'];
  const table = (heads, rows) => `<div class="dl-table-wrap"><table class="os-table dl-table"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const title = (n,t,note='') => `<h2>${n}. ${t}<small>${note}</small></h2>`;
  const note = t => `<p class="dl-note">${t}</p>`;
  const icon = (name, color='#168cff') => {
    const paths={person:'<circle cx="12" cy="6" r="4"/><path d="M4 23v-4a8 8 0 0 1 16 0v4z"/>',group:'<circle cx="12" cy="5" r="3"/><circle cx="4" cy="8" r="2.5"/><circle cx="20" cy="8" r="2.5"/><path d="M7 22v-8a5 5 0 0 1 10 0v8zM1 21v-7a3 3 0 0 1 5-2v9zM18 21v-9a3 3 0 0 1 5 2v7z"/>',alert:'<path d="M10 3a2 2 0 0 1 4 0l10 18H0z"/><path d="M12 8v6m0 3v1" stroke="white" stroke-width="2"/>',bell:'<path d="M4 17V9a8 8 0 0 1 16 0v8l3 3H1zM9 22h6a3 3 0 0 1-6 0"/>',clock:'<circle cx="12" cy="12" r="11"/><path d="M12 5v8l5 3" fill="none" stroke="white" stroke-width="2"/>',building:'<path d="M2 22V7h6v15M9 22V2h7v20M17 22V10h5v12" fill="none" stroke="currentColor" stroke-width="2"/><path d="M4 10h2m-2 4h2m5-8h3m-3 4h3m-3 4h3m5 0h2" stroke="currentColor" stroke-width="2"/>',robot:'<path d="M3 7h18v15H3zM11 2h2v5H11zM0 11h2v8H0zM22 11h2v8h-2z"/><path d="M7 12h3m4 0h3M8 18h8" stroke="white" stroke-width="2"/>',up:'<path d="M12 1 2 11h6v12h8V11h6z"/>'};
    Object.assign(paths,{
      clipboard:'<rect x="4" y="4" width="16" height="19" rx="2"/><rect x="8" y="1" width="8" height="5" rx="2" stroke="white"/><path d="M8 10h8M8 14h6M8 18h5" stroke="white" fill="none"/>',
      shield:'<path d="M12 1 2 5v7c0 6 10 11 10 11s10-5 10-11V5z"/><path d="m6 11 4 4 8-8" fill="none" stroke="white" stroke-width="2"/>',
      link:'<circle cx="12" cy="12" r="11"/><path d="m10 8 3-3a4 4 0 0 1 6 6l-3 3m-2 2-3 3a4 4 0 0 1-6-6l3-3m1 5 6-6" fill="none" stroke="white" stroke-width="1.7"/>',
      check:'<circle cx="12" cy="12" r="11"/><path d="m6 12 4 4 8-8" fill="none" stroke="white" stroke-width="2"/>',
      fileAlert:'<rect x="4" y="4" width="16" height="19" rx="3"/><rect x="9" y="1" width="6" height="6" rx="2" stroke="white"/><path d="M12 10v6m0 2v2" stroke="white" stroke-width="2"/>'
    });
    return `<svg class="dl-icon" viewBox="0 0 24 24" aria-hidden="true" style="color:${color};fill:${color}">${paths[name]||paths.building}</svg>`;
  };
  const {data:d,totals:t,sum,percent}=window.DashboardLatestData;
  const f=n=>Number(n).toLocaleString('en-US');
  const rate=(n,total)=>percent(n,total)+'%';
  const bar=(n,total)=>`<div class="dv-rate"><div class="dv-chart" data-value="${percent(n,total)}" role="img" aria-label="${rate(n,total)}"></div><span>${rate(n,total)}</span></div>`;
  const step=(index,label,value,symbol,lower,green=false)=>`<div class="dv-stage"><div class="dv-step ${green?'green':''}"><i>${index}</i>${icon(symbol,green?'#13c7ae':'#168cff')}<h3>${label}</h3><b>${f(value)}<small> 人</small></b></div><div class="dv-stem"></div>${lower}</div>`;
  const branch=(label,value,symbol,color='orange',extra='')=>`<div class="dv-branch ${color}">${icon(symbol,color==='orange'?'#ff7900':color==='green'?'#13c7ae':'#8699b7')}<div>${label}</div><b>${f(value)} <small>人</small></b>${extra}</div>`;
  const arrow=(label,n,total)=>`<div class="dv-arrow"><span>${label}</span><b>${rate(n,total)}</b><i></i></div>`;
  const levelRows=d.levels.map(r=>[dot(r.color)+r.name,f(r.due),f(r.active),`<span class="dl-red">${f(r.due-r.active)}</span>`,rate(r.active,r.due),r.evaluable===null?'—':f(r.evaluable),r.standard===null?'—':f(r.standard),r.standard===null?'—':rate(r.standard,r.evaluable)]);
  levelRows.push(['合计',f(t.managedDue),f(t.active),`<span class="dl-red">${f(t.managedDue-t.active)}</span>`,rate(t.active,t.managedDue),f(sum(d.levels,'evaluable')),f(sum(d.levels,'standard')),rate(sum(d.levels,'standard'),sum(d.levels,'evaluable'))]);
  const orgRows=[{name:'区域合计',...t},...d.organizations];
  const orgTable=`<div class="dl-table-wrap"><table class="os-table dl-table"><thead><tr><th rowspan="2">机构</th><th colspan="5">本期筛查人群</th><th colspan="3">全部来源 · 期末</th><th rowspan="2">操作</th></tr><tr>${['应筛（人）','已筛（人）','异常（人）','符合入组（人）','已入组（人）','应管理（人）','在管（人）','未在管（人）'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${orgRows.map((r,i)=>`<tr>${[r.name,...['due','screened','abnormal','eligible','enrolled','managedDue','active'].map(k=>f(r[k])),`<span class="dl-red">${f(r.managedDue-r.active)}</span>`,i?`<button class="dl-org-link" data-org="${r.name}">查看</button>`:'—'].map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const referralRow=r=>[r.name,f(r.up),f(r.up-r.upClosed),rate(r.upClosed,r.up),f(r.down),f(r.down-r.downClosed),rate(r.downClosed,r.down)];
  const referralTotal={name:'区域合计',...Object.fromEntries(['up','upClosed','down','downClosed'].map(k=>[k,sum(d.referrals,k)]))};
  const flow=(down)=>{const a=d.referralStages[down?'down':'up'];return `<div class="dv-referral ${down?'down':''}"><h3>${icon('up',down?'#14c8ad':'#168cff')}向${down?'下':'上'}转诊</h3>${['申请','已接收',down?'管理交接':'已到院',down?'首次服务完成':'诊疗反馈完成'].map((x,i)=>`<div>${x}<b>${a[i]} 单</b></div>${i<3?'<em>→</em>':''}`).join('')}<strong>${down?'下':'上'}转闭环率<b>${rate(a[3],a[0])}</b></strong></div>`;};
  root.innerHTML=`<div class="dl-dashboard dv-dashboard">
    <header class="dl-header"><h1>AI患者运营管理驾驶舱</h1><span class="dl-subtitle">区域总览 · 人群覆盖 · 机构分布</span><span class="dl-badge">演示数据</span><span>统计截至 ${d.end}</span></header>
    <div id="dlFilters" class="dl-filters"></div><div class="dl-scope"><span>当前范围： 区域总览 / 全部机构</span></div><div id="dlMessage" role="status" hidden></div>
    <section class="dl-card dv-overview">${title(1,'人群与管理总览')}<span class="dl-included">纳入统计人群 <b>${f(d.population)}</b> 人</span>
    <div class="dv-funnel-layout dv-funnel-integrated"><div class="dv-funnel-panel"><h3>筛查入组转化漏斗</h3><p>比率展示在相邻漏斗层之间，表示下一阶段人数占上一阶段人数的比例</p><div class="dv-funnel-canvas"><div id="dvOverviewFunnel" role="img" aria-label="总体人数10000人，筛查覆盖率60.0%，已筛查6000人，异常率20.0%，筛查异常1200人，入组适配率83.3%，符合入组1000人，入组转化率80.0%，已入组800人"></div><div class="dv-funnel-ratios">${[['筛查覆盖率',t.screened,t.due],['异常率',t.abnormal,t.screened],['入组适配率',t.eligible,t.abnormal],['入组转化率',t.enrolled,t.eligible]].map(([name,n,den],i)=>`<span class="dv-gap-ratio" style="top:${85+i*90}px">↓ ${name} <b>${rate(n,den)}</b></span>`).join('')}</div></div><p class="dv-funnel-caption">各层宽度按人数同比例展示 · 总体入组占比 <b>${rate(t.enrolled,t.due)}</b></p></div></div>
    <div class="dv-summary"><h3>${icon('group')}全部来源 · 当前管理情况</h3><div>${icon('person')}<span>应管理<b>${f(t.managedDue)} <small>人</small></b></span></div><div class="teal">${icon('person','#14c8ad')}<span>当前在管<b>${f(t.active)} <small>人</small></b></span></div><div class="dl-red">${icon('person','#ff8a00')}<span>未在管<b>${f(t.managedDue-t.active)} <small>人</small></b></span></div><div>${icon('clock')}<span>管理覆盖率<b>${rate(t.active,t.managedDue)}</b></span></div><p>筛查转化跟随同一批人；<br>当前在管包含历史入组及其他来源患者。</p></div>
    </section>
    <section class="dl-card dv-org dv-org-pies"><div class="dv-org-heading">${title(2,'机构覆盖与管理分布','已筛查、已入组及在管人群，分别分布在哪些机构')}<span class="dl-badge">演示数据</span><button type="button" id="dvFullData" aria-expanded="false" aria-controls="dvOrgDetails">查看完整数据 ›</button></div><div class="dv-org-scope"><span>当前范围：<b>全部机构</b></span><span>机构 → 科室 → 团队 → 个人</span></div><div class="dv-org-three">${[['screened','已筛查人群分布','本期筛查'],['enrolled','已入组人群分布','本期筛查入组'],['active','当前在管人群分布','全部来源 · 期末']].map(([key,label,subtitle])=>`<article><h3>${label}</h3><p>${subtitle}</p><strong>${f(t[key])} <small>人</small></strong><div class="dv-org-pie" data-org-metric="${key}" role="img" aria-label="${label}，总计${t[key]}人"></div><div class="dv-org-legend">${d.organizations.map((r,i)=>`<button type="button" data-org="${r.name}" aria-label="查看${r.name}${label}">${dot(['#287fff','#1fc1b3','#9780ef'][i])}<b>${r.name}</b><span>${f(r[key])} 人</span><em>${rate(r[key],t[key])}</em></button>`).join('')}</div></article>`).join('')}</div><div class="dv-org-gaps"><span>本期未筛查 <b>${f(t.due-t.screened)}</b> 人</span><span>符合条件未入组 <b>${f(t.eligible-t.enrolled)}</b> 人</span><span>当前未在管 <b>${f(t.managedDue-t.active)}</b> 人</span></div>${note('饼图占比 = 该机构人数 ÷ 区域同类人群总人数；不代表该机构的管理覆盖率。')}${note('按唯一主责机构统计；点击机构查看机构概览。各图统计范围以标题说明为准。')}<div id="dvOrgDetails" hidden>${orgTable}</div></section>
    <section class="dl-card dv-levels">${title(3,'三色管理','当前应管理人群：分级、覆盖与规范管理')}<div class="dl-risk-grid"><div class="dl-pie-panel"><div id="dlPie" class="dl-pie" role="img" aria-label="应管理人群 2560 人的等级分布"></div><div><h3>应管理人群 <b>${f(t.managedDue)}</b> 人</h3>${d.levels.map(r=>`<p>${dot(r.color)}${r.name}　${f(r.due)} 人（${rate(r.due,t.managedDue)}）</p>`).join('')}</div></div><div>${table(['等级','应管理（人）','在管（人）','未在管（人）','覆盖率','可评价（人）','规范人数（人）','规范管理率'],levelRows)}${note(`已分级在管 <b>${f(sum(d.levels.slice(0,3),'active'))}</b> 人 = 规范 <b>${f(sum(d.levels,'standard'))}</b> + 不规范 ${sum(d.levels,'evaluable')-sum(d.levels,'standard')} + 尚未到评价时间 <b>${sum(d.levels.slice(0,3),'active')-sum(d.levels,'evaluable')}</b>；未分级另计。`)}</div></div><div class="dv-cycle">${icon('clock')}本期到期管理周期（非当前在管人数）：<span>应完成 <b>${d.cycles.due}</b> 个</span><span>正常完成 <b>${d.cycles.completed}</b> 个</span><span>周期完成率 <b>${rate(d.cycles.completed,d.cycles.due)}</b></span></div></section>
    <section class="dl-card dv-outcomes">${title(4,'健康管理成效','按病种独立评价')}<div class="dv-eval"><span>${icon('clipboard')}到期应评价 <b>${f(d.evaluationDue)}</b> 例</span><span>${icon('check')}可评价 <b>${f(sum(d.outcomes,'evaluable'))}</b> 例</span><span>${icon('clock','#ff7900')}待评价 <b>${d.evaluationDue-sum(d.outcomes,'evaluable')}</b> 例</span></div>${table(['病种','成效指标','可评价病例（例）','达到目标病例（例）','达标或稳定比例'],d.outcomes.map(r=>[r.name,r.metric,r.evaluable,r.achieved,bar(r.achieved,r.evaluable)]))}${note('评价目标与观察窗口按院内病种规则确定；不同病种结果不直接平均。以上为演示数据。')}</section>
    <section class="dl-card dv-safety">${title(5,'风险与安全')}<div class="dv-safety-stats">${[['alert','高危预警患者',sum(d.risks,'high'),'人','#ff506b'],['bell','未处置预警',sum(d.risks,'unhandled'),'次','#ff7900'],['clock','其中超时未处置',sum(d.risks,'overdue'),'次','#ff506b'],['shield','及时处置率',d.riskTotals.timely.toFixed(1)+'%','','#168cff'],['link','预警闭环率',d.riskTotals.closed.toFixed(1)+'%','','#14c8ad']].map(a=>`<div>${icon(a[0],a[4])}<span>${a[1]}<b>${a[2]} <small>${a[3]}</small></b></span></div>`).join('')}<div>已处置未闭环 <b>${d.riskTotals.handledOpen}</b> 次</div></div>${table(['机构','高危患者（人）','未处置（次）','其中超时（次）','及时处置率','预警闭环率'],d.risks.map(r=>[r.name,r.high,`<span class="dl-red">${r.unhandled}</span>`,`<span class="dl-red">${r.overdue}</span>`,bar(r.timely,100),bar(r.closed,100)]))}${note('按底层期末统计；比率按各自到期预警事件计算。高危预警与三色管理等级分别统计。')}</section>
    <section class="dl-card dv-referrals">${title(6,'双向转诊')}<div class="dv-flows">${flow(false)}${flow(true)}</div>${table(['机构','上转申请（单）','上转未闭环（单）','上转闭环率','下转申请（单）','下转未闭环（单）','下转闭环率'],[referralTotal,...d.referrals].map(referralRow))}${note('按本期申请单跟踪；完成诊疗反馈或首次服务并确认结果后闭环。')}</section>
    <footer class="dl-footer">演示数据仅用于界面评审 · 患者按人去重，病例、周期与事件分别统计</footer>
    <dialog id="dlDialog"><h2>机构管理概览</h2><p id="dlDialogText"></p><button id="dlClose" type="button">关闭</button></dialog>
  </div>`;
  const instances=[];
  function chart(el,option){if(!window.echarts)return;const c=echarts.getInstanceByDom(el)||echarts.init(el);c.setOption({animation:false,textStyle:{fontFamily:'Microsoft YaHei'},...option},true);if(!instances.includes(c))instances.push(c);}
  // Same local ECharts runtime and standard pie/bar options as statistics-report.js.
  function render(){if(!root.classList.contains('active'))return;requestAnimationFrame(()=>{
    const funnelNotes=[`未筛查 ${f(t.due-t.screened)} 人`,`未见异常 ${f(t.screened-t.abnormal)} 人`,`不符合入组 ${f(d.ineligible)} 人`,`符合条件未入组 ${f(t.eligible-t.enrolled)} 人 · 其中超期 ${d.overdueEnrollment} 人`,`该批期末仍在管 ${f(d.cohortActive)} 人`];
    chart(document.getElementById('dvOverviewFunnel'),{tooltip:{trigger:'item',confine:true,formatter:p=>p.name+'<br>'+f(p.value)+' 人<br>占总体人数 '+rate(p.value,t.due)+'<br>'+funnelNotes[p.dataIndex]},series:[{type:'funnel',left:'20%',top:10,bottom:10,width:'50%',min:0,max:t.due,minSize:'0%',maxSize:'100%',sort:'none',gap:30,funnelAlign:'center',label:{show:true,position:'right',fontSize:13,lineHeight:22,color:'#173c83',formatter:p=>'{stage|'+p.name+'  '+f(p.value)+' 人}\n{note|'+funnelNotes[p.dataIndex]+'}',rich:{stage:{fontSize:14,fontWeight:700,lineHeight:24,color:'#173c83'},note:{fontSize:10,lineHeight:18,color:'#7b8eac'}}},labelLine:{show:true,length:18,lineStyle:{color:'#9fc5e7'}},itemStyle:{borderColor:'#fff',borderWidth:1},emphasis:{label:{fontWeight:700}},data:[['总体人数',t.due,'#1677ff'],['已筛查',t.screened,'#3697f4'],['筛查异常',t.abnormal,'#53a9e7'],['符合入组',t.eligible,'#35b9c1'],['已入组',t.enrolled,'#14b89d']].map(([name,value,color])=>({name,value,itemStyle:{color}}))}]});
    root.querySelectorAll('[data-org-metric]').forEach(el=>{const key=el.dataset.orgMetric;chart(el,{tooltip:{trigger:'item',confine:true,formatter:p=>p.name+'<br>'+f(p.value)+' 人（'+rate(p.value,t[key])+'）'},series:[{type:'pie',radius:'92%',center:['50%','50%'],startAngle:90,clockwise:true,itemStyle:{borderColor:'#fff',borderWidth:1},label:{show:true,position:'inside',color:'#fff',fontSize:15,fontWeight:700,formatter:p=>rate(p.value,t[key])},emphasis:{scaleSize:5},data:d.organizations.map((r,i)=>({name:r.name,value:r[key],itemStyle:{color:['#287fff','#1fc1b3','#9780ef'][i]}}))}]});const c=echarts.getInstanceByDom(el);c.off('click');c.on('click',p=>root.querySelector('.dv-org-legend [data-org="'+p.name+'"]')?.click());});
    chart(document.getElementById('dlPie'),{tooltip:{trigger:'item',confine:true,formatter:p=>`${p.name}<br>${f(p.value)} 人（${rate(p.value,t.managedDue)}）`},series:[{type:'pie',radius:'85%',center:['48%','53%'],startAngle:90,itemStyle:{borderWidth:1,borderColor:'#fff'},label:{show:true,position:'inside',color:'#fff',fontWeight:700,fontSize:14,formatter:p=>rate(p.value,t.managedDue)},data:d.levels.map(r=>({name:r.name,value:r.due,itemStyle:{color:r.color},...(r.name==='未分级'?{label:{position:'outside',color:'#10139d',fontSize:11},labelLine:{length:3,length2:1}}:{})}))}]});
    root.querySelectorAll('.dv-chart').forEach(el=>chart(el,{grid:{left:0,right:0,top:0,bottom:0},tooltip:{trigger:'item',confine:true,formatter:()=>el.dataset.value+'%'},xAxis:{type:'value',max:100,show:false},yAxis:{type:'category',show:false},series:[{type:'bar',data:[Number(el.dataset.value)],barWidth:12,showBackground:true,backgroundStyle:{color:'#dbe3eb',borderRadius:2},itemStyle:{borderRadius:2,color:new echarts.graphic.LinearGradient(0,0,1,0,[{offset:0,color:'#52b4fa'},{offset:1,color:'#258ffc'}])}}]}));instances.forEach(c=>c.resize());});}
  window.renderDashboardLatest=render;
  new ResizeObserver(()=>{if(root.classList.contains('active'))instances.forEach(c=>c.resize());}).observe(root);
  document.getElementById('dvFullData').onclick=()=>{const panel=document.getElementById('dvOrgDetails');panel.hidden=!panel.hidden;const btn=document.getElementById('dvFullData');btn.setAttribute('aria-expanded',String(!panel.hidden));btn.textContent=panel.hidden?'查看完整数据 ›':'收起完整数据 ⌃';};
  const dialog=document.getElementById('dlDialog');document.getElementById('dlClose').onclick=()=>dialog.close();
  root.querySelectorAll('[data-org]').forEach(btn=>btn.onclick=()=>{const r=d.organizations.find(r=>r.name===btn.dataset.org);document.getElementById('dlDialogText').textContent=`${r.name}：应筛 ${f(r.due)} 人，已筛 ${f(r.screened)} 人，异常 ${r.abnormal} 人，符合入组 ${r.eligible} 人，已入组 ${r.enrolled} 人。全部来源应管理 ${f(r.managedDue)} 人，在管 ${f(r.active)} 人，未在管 ${r.managedDue-r.active} 人。未提供科室级数据，暂不展示下级明细。`;dialog.showModal();});
  StatisticsFilters.mount(document.getElementById('dlFilters'),v=>{const msg=document.getElementById('dlMessage');const baseline=!v.org&&!v.dept&&!v.team&&!v.person&&!v.disease&&v.start===d.start&&v.end===d.end;msg.hidden=baseline;msg.textContent='当前仅提供 2026 年 7 月区域总览演示数据。所选范围尚无数据，仍展示原图口径；点击重置可恢复默认查询。';},{orgs:{A机构:[],B机构:[],C机构:[]},people:[],diseases:d.outcomes.map(r=>r.name)},{start:d.start,end:d.end},{variant:'operations',orgLabel:'全部机构',applyOnChange:false});
  if(new URLSearchParams(location.search).get('view')==='dashboardLatest')showListView('dashboardLatest');
})();
