/* Latest dashboard: screenshot-aligned demonstration, isolated from existing reports. */
(() => {
  const root = document.getElementById('dashboardLatestView');
  if (!root) return;
  const dot = (color) => `<i class="dl-dot" style="background:${color}"></i>`;
  const colors = ['#ff506b','#ffd647','#14c8ad','#9bb4ce'];
  const table = (heads, rows) => `<div class="dl-table-wrap"><table class="os-table dl-table"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const title = (n,t,note='') => `<h2>${n}. ${t}<small>${note}</small></h2>`;
  const note = t => `<p class="dl-note">${t}</p>`;
  const icon = (name, color='#168cff') => {
    const paths={person:'<circle cx="12" cy="6" r="4"/><path d="M4 23v-4a8 8 0 0 1 16 0v4z"/>',group:'<circle cx="12" cy="5" r="3"/><circle cx="4" cy="8" r="2.5"/><circle cx="20" cy="8" r="2.5"/><path d="M7 22v-8a5 5 0 0 1 10 0v8zM1 21v-7a3 3 0 0 1 5-2v9zM18 21v-9a3 3 0 0 1 5 2v7z"/>',alert:'<path d="M10 3a2 2 0 0 1 4 0l10 18H0z"/><path d="M12 8v6m0 3v1" stroke="white" stroke-width="2"/>',bell:'<path d="M4 17V9a8 8 0 0 1 16 0v8l3 3H1zM9 22h6a3 3 0 0 1-6 0"/>',clock:'<circle cx="12" cy="12" r="11"/><path d="M12 5v8l5 3" fill="none" stroke="white" stroke-width="2"/>',building:'<path d="M2 22V7h6v15M9 22V2h7v20M17 22V10h5v12" fill="none" stroke="currentColor" stroke-width="2"/><path d="M4 10h2m-2 4h2m5-8h3m-3 4h3m-3 4h3m5 0h2" stroke="currentColor" stroke-width="2"/>',robot:'<path d="M3 7h18v15H3zM11 2h2v5H11zM0 11h2v8H0zM22 11h2v8h-2z"/><path d="M7 12h3m4 0h3M8 18h8" stroke="white" stroke-width="2"/>',up:'<path d="M12 1 2 11h6v12h8V11h6z"/>'};
    return `<svg class="dl-icon" viewBox="0 0 24 24" aria-hidden="true" style="color:${color};fill:${color}">${paths[name]||paths.building}</svg>`;
  };
  const orgRows = [['区域合计','6,000','800','2,560','2,200','28','112','360'],['A机构','3,000','400','1,160','1,000','14','60','160'],['B机构','2,000','240','820','700','8','32','120'],['C机构','1,000','160','580','500','6','20','80']];
  const flow = (down,nums,rate) => `<div class="dl-flow ${down?'down':''}"><h3>${icon('building',down?'#08b7ad':'#168cff')}向${down?'下':'上'}转诊</h3><div class="dl-flow-steps">${[ '申请','已接收',down?'管理交接':'已到院',down?'首次随访完成':'诊疗反馈完成'].map((x,i)=>`<div>${x}<b>${nums[i]} <small>单</small></b></div>${i<3?'<span>→</span>':''}`).join('')}<strong>${down?'下':'上'}转闭环率<b>${rate}%</b></strong></div></div>`;
  root.innerHTML=`<div class="dl-dashboard">
    <header class="dl-header"><h1>AI患者运营管理驾驶舱</h1><span class="dl-subtitle">区域总览 · 管理覆盖 · 机构分布</span><span class="dl-badge">演示数据</span><span>统计截至 <b>2026-07-31</b></span></header>
    <div id="dlFilters" class="dl-filters"></div>
    <div class="dl-scope"><span id="dlScope">当前范围： 区域总览 / 全部机构</span><button id="dlMetric" type="button">统计口径 ›</button></div>
    <div id="dlMessage" role="status" hidden></div>
    <div class="dl-overview">
      <section class="dl-card">${title(1,'人群与管理总览')}<span class="dl-included">纳入统计人群 <b>12,000</b> 人</span><div class="dl-cohort"><div class="dl-cohort-line">本期应筛 <b>10,000</b> 人 <span class="dl-right dl-warn">未筛查 <b>4,000</b> 人</span></div><div class="dl-screened"><div class="dl-cohort-line">已筛查 <b>6,000</b> 人 · <small>覆盖率</small> 60.0% <span class="dl-right"><small>未见筛查异常</small> 4,800 人</span></div><div class="dl-abnormal"><div class="dl-cohort-line">筛查异常 <b>1,200</b> 人 · <small>异常率</small> 20.0% <span class="dl-right"><small>待评估 80 人 · 不符合入组 120 人</small></span></div><div class="dl-eligible">符合入组 <b>1,000</b> 人<div class="dl-enrolled"><div>${icon('person','#13c7ae')}已入组 <b>800</b> 人 · <small>转化率</small> 80.0%</div><div>${icon('group','#ff8100')}<span class="dl-red">未入组 <b>200</b> 人</span><span class="dl-orange">◷ 其中超期 60 人</span></div></div></div></div></div><div class="dl-cohort-line">本批期末仍在管 <b>720</b> 人</div></div></section>
      <section class="dl-card dl-current"><h3>全部来源 · 当前应管理</h3><div class="dl-big">2,560 <small>人</small></div><div class="dl-current-pair"><div>${icon('person')}<span>当前在管<b>2,200 <small>人</small></b></span></div><div>${icon('group','#ff8100')}<span class="dl-red">未在管<b>360 <small>人</small></b></span></div></div><h3>管理覆盖率 85.9%</h3><div class="dl-progress-row"><div id="dlCoverage" class="dl-progress-chart"></div><b>85.9%</b></div>${note('左侧为本期筛查队列；右侧包含历史及其他来源的当前需管理对象。')}</section>
    </div>
    <section class="dl-card dl-org">${title(2,'机构覆盖与管理分布')}<span class="dl-included">机构 → 科室 → 团队 → 个人</span>${table(['机构','本期筛查','筛查入组','当前应管','当前在管','红色未管','黄色未管','未管合计'],orgRows.map((r,i)=>r.map((v,j)=>j===0&&i?`<button class="dl-org-link" data-org="${v}">${v} ›</button>`:v)))}${note('点击机构查看该机构演示概览；人数为截图演示口径。')}</section>
    <section class="dl-card">${title(3,'三色人群覆盖与规范管理','统计对象：当前应管理的人群，包含未筛查患者')}<div class="dl-risk-grid"><div class="dl-pie-panel"><div id="dlPie" class="dl-pie" aria-label="应管理人群分布饼图"></div><div><h3>应管理人群分布 · 2,560 人</h3>${['红色　160 人 (6.3%)','黄色　640 人 (25.0%)','绿色　1,700 人 (66.4%)','未分级　60 人 (2.3%)'].map((t,i)=>`<p>${dot(colors[i])}${t}</p>`).join('')}</div></div><div>${table(['等级','应管理','当前在管','未在管','覆盖率','可评价人数','规范人数','规范管理率'],[['红色','160','132','28','82.5%','120','108','90.0%'],['黄色','640','528','112','82.5%','480','408','85.0%'],['绿色','1,700','1,496','204','88.0%','1,360','1,224','90.0%'],['未分级','60','44','16','73.3%','—','—','—'],['合计','2,560','2,200','360','85.9%','1,960','1,740','88.8%']].map((r,i)=>r.map((v,j)=>j===0&&i<4?dot(colors[i])+v:v)))}${note('已分级在管 <b>2,156 人</b> = 规范 <b>1,740</b> + 不规范 220 + 尚未到评价时间 <b>196</b>　 规范管理率按可评价人数计算；未分级暂不参与分级规范评价。')}</div></div></section>
    <div class="dl-two"><section class="dl-card">${title(4,'双向转诊','区域汇总与机构承接情况')}${flow(false,[240,228,216,204],'85.0')}${flow(true,[180,168,152,144],'80.0')}${table(['机构','上转申请','上转闭环率','下转申请','下转闭环率'],[['A机构 ›','120','90.0%','80','85.0%'],['B机构 ›','80','80.0%','60','70.0%'],['C机构 ›','40','80.0%','40','85.0%']])}${note('本期申请队列；完成总数晚于次日转诊确认结果后展示。')}</section>
    <section class="dl-card">${title(5,'风险与安全','区域风险汇总与机构对比')}<div class="dl-alerts">${[['alert','高危预警患者','18','人','#ff506b'],['bell','未处置预警','30','次','#ff8100'],['clock','其中超时未处置','8','次','#ff506b']].map(a=>`<div>${icon(a[0],a[4])}<span>${a[1]}<b>${a[2]} <small>${a[3]}</small></b></span></div>`).join('')}</div><div class="dl-rates"><div><h3>及时处置率 90.0%</h3><div id="dlTimely" class="dl-progress-chart"></div></div><div><h3>预警闭环率 85.0%</h3><div id="dlClosed" class="dl-progress-chart"></div></div><span>已处置未闭环 16 次</span></div>${table(['机构','高危患者(人)','未处置(次)','其中超时(次)','及时率','闭环率'],[['A机构 ›',8,14,4,'90.0%','90.0%'],['B机构 ›',6,10,3,'85.0%','75.0%'],['C机构 ›',4,6,1,'95.0%','85.0%']])}${note('按底层原因归类；比率按各自本期归属预警计算，高危预警与三色等级分别统计。')}</section></div>
    <section class="dl-card dl-change">${title(6,'人群结构与管理变化')}<div class="dl-equation"><span>期初在管<b>1,500 人</b></span><em>+</em><span>本期进入<b>1,000 人</b></span><em>−</em><span>本期退出<b>300 人</b></span><em>=</em><span>服务总量<b>2,200 人</b></span><span class="dl-net">${icon('up','#13c7ae')}净增加<b>700 人</b></span></div><div class="dl-four"><div><h3>${icon('building')}管理周期完成</h3>${table(['等级','应脱组','正常完成','完成率'],[['红色',40,32,'80.0%'],['黄色',100,86,'86.0%'],['绿色',160,144,'90.0%']].map((r,i)=>r.map((v,j)=>j===0?dot(colors[i])+v:v)))}<b class="dl-total">合计　262 / 300 个周期 · 87.3%</b>${note('按本期到期周期及周期开始等级统计，与当前在管人数分开。')}</div><div><h3>${icon('building')}未在管原因分布</h3><p>未在管 <b>360 人</b></p><div id="dlReasons" class="dl-bars"></div>${note('含历史脱组，每人按主要原因归类。')}</div><div><h3>${icon('building')}在管病种分布</h3><div id="dlDiseases" class="dl-bars dl-tall"></div>${note('共 2,800 例；患者可涉及多个病种。')}</div><div><h3>${icon('building')}新增入组来源</h3><p>全部来源期入组 <b>1,000 人</b></p><div id="dlSources" class="dl-stack"></div><div class="dl-source-labels">${['筛查|800 人 · 80%','门诊|120 人 · 12%','出院|80 人 · 8%'].map((t,i)=>`<div>${dot(['#168cff','#14c8ad','#80b9ff'][i])}${t.split('|').join('<br>')}</div>`).join('')}</div>${note('按首次入组来源归类。')}</div></div></section>
    <div class="dl-two"><section class="dl-card">${title(7,'健康管理成效','各病种分别评价 · 院内规则演示')}<div class="dl-mini-stats"><span>◉ 到期需评价 <b>2,000 例</b></span><span>↓ 可评价 <b>1,700 例</b></span><span>♟ 待评价 <b>300 例</b></span></div>${table(['病种','成效指标','可评价','达到目标','结果'],[['CKD','eGFR稳定','400 例','320 例','<div class="dl-result" data-rate="80"></div>'],['高血压','血压达标','700 例','525 例','<div class="dl-result" data-rate="75"></div>'],['糖尿病','HbA1c达标','600 例','420 例','<div class="dl-result" data-rate="70"></div>']])}${note('各病种按院内服务完成规则可评价，不直接干预不同底层依据。')}</section>
    <section class="dl-card">${title(8,'AI应用与资源效率','服务完成与人工投入 · 演示测算')}<div class="dl-ai-stats">${[['robot','AI服务量','1,760 人','占在管人数 80.0%'],['building','AI独立完成率','78.0%','780 / 1,000 项'],['person','人工接管率','16.0%','160 / 1,000 项']].map(a=>`<div>${icon(a[0])}<span>${a[1]}<b>${a[2]}</b>${a[3]}</span></div>`).join('')}</div><div class="dl-two dl-ai-bottom"><div><h3>服务完成构成（1,000 项）</h3><div id="dlAi" class="dl-stack"></div><p class="dl-legend">${dot('#168cff')}AI独立完成 780 项　${dot('#14c8ad')}转人工 160 项　${dot('#80b9ff')}执行失败 60 项</p></div><div><h3>同量服务人工工时 · 测算示例</h3><div id="dlHours" class="dl-hours"></div><b class="dl-saved">估算减少 42 小时</b>${note('人工投入含审核、接管改正；以工时记录核验。')}</div></div></section></div>
    <footer class="dl-footer"><span><span class="dl-badge">演示数据</span>　AI赋能医疗 · 精细化管理 · 更直接的区域人群</span><span>演示数据仅用于界面评审，最终经人工审核，数例与周期分别统计</span></footer>
    <dialog id="dlDialog"><h2>统计口径</h2><p id="dlDialogText"></p><button type="button" id="dlClose">关闭</button></dialog>
  </div>`;
  const instances=[];
  const chart=(id,opt)=>{const el=typeof id==='string'?document.getElementById(id):id;if(!el||!window.echarts)return;const c=echarts.getInstanceByDom(el)||echarts.init(el);c.setOption({animation:false,textStyle:{fontFamily:'Microsoft YaHei',color:'#2427bb',fontSize:11},...opt},true);if(!instances.includes(c))instances.push(c);};
  function bars(id,labels,values,max,unit='人') {chart(id,{grid:{left:65,right:48,top:3,bottom:3},tooltip:{trigger:'axis',confine:true,axisPointer:{type:'shadow'}},xAxis:{type:'value',max,show:false},yAxis:{type:'category',inverse:true,data:labels,axisLine:{show:false},axisTick:{show:false},axisLabel:{fontSize:10,color:'#5965c4'}},series:[{type:'bar',data:values,barWidth:14,itemStyle:{borderRadius:2,color:new echarts.graphic.LinearGradient(0,0,1,0,[{offset:0,color:'#57b5ff'},{offset:1,color:'#2693fc'}])},label:{show:true,position:'right',formatter:`{c} ${unit}`,color:'#3638d5',fontSize:10}}]});}
  function progress(id,rate,color='#2693fc'){chart(id,{grid:{left:0,right:0,top:0,bottom:0},xAxis:{type:'value',max:100,show:false},yAxis:{type:'category',show:false},series:[{type:'bar',data:[rate],barWidth:14,showBackground:true,backgroundStyle:{color:'#d9e5ed',borderRadius:7},itemStyle:{color,borderRadius:7}}]});}
  function stack(id,values){chart(id,{grid:{left:0,right:0,top:0,bottom:0},tooltip:{trigger:'item',confine:true},xAxis:{type:'value',max:100,show:false},yAxis:{type:'category',show:false},series:values.map((v,i)=>({name:['第一类','第二类','第三类'][i],type:'bar',stack:'total',barWidth:23,data:[v],itemStyle:{color:['#168cff','#14c8ad','#80b9ff'][i]},label:{show:true,position:'inside',formatter:'{c}%',color:'#fff',fontSize:11}}))});}
  function render(){if(!root.classList.contains('active'))return;requestAnimationFrame(()=>{chart('dlPie',{tooltip:{trigger:'item',confine:true,formatter:'{b}<br>{c} 人 ({d}%)'},series:[{type:'pie',radius:'88%',center:['50%','54%'],startAngle:90,minAngle:2,itemStyle:{borderColor:'#fff',borderWidth:1},label:{show:true,position:'inside',formatter:p=>p.percent<4?'':p.percent.toFixed(1)+'%',fontSize:14,fontWeight:700,color:'#fff'},data:[160,640,1700,60].map((v,i)=>({value:v,name:['红色','黄色','绿色','未分级'][i],itemStyle:{color:colors[i]}}))}]});progress('dlCoverage',85.9);progress('dlTimely',90);progress('dlClosed',85,'#14c8ad');bars('dlReasons',['未入组','管理中断','转诊等衔接'],[260,64,36],260);bars('dlDiseases',['高血压','糖尿病','CKD','乳腺结节'],[900,900,600,400],1000,'例');stack('dlSources',[80,12,8]);stack('dlAi',[78,16,6]);bars('dlHours',['人工基线','AI辅助后'],[50,8],50,'小时');root.querySelectorAll('.dl-result').forEach(el=>{progress(el,+el.dataset.rate);el.setAttribute('aria-label',el.dataset.rate+'.0%');});instances.forEach(c=>c.resize());});}
  window.renderDashboardLatest=render;
  new ResizeObserver(()=>{if(root.classList.contains('active'))instances.forEach(c=>c.resize());}).observe(root);
  const dialog=document.getElementById('dlDialog');
  const showDialog=t=>{document.getElementById('dlDialogText').textContent=t;dialog.showModal();};
  document.getElementById('dlMetric').onclick=()=>showDialog('本页面按提供的 2026 年 7 月截图展示演示数据。应管理人数 2,560 人，当前在管 2,200 人，覆盖率 85.9%。规范管理率分母为可评价人数；病种按病例分别统计。筛选条件仅用于演示范围选择，尚未接入真实数据接口。');
  document.getElementById('dlClose').onclick=()=>dialog.close();
  root.querySelectorAll('[data-org]').forEach(btn=>btn.onclick=()=>{const r=orgRows.find(r=>r[0]===btn.dataset.org);showDialog(`${r[0]}：本期筛查 ${r[1]} 人，筛查入组 ${r[2]} 人，当前应管 ${r[3]} 人，当前在管 ${r[4]} 人，未管合计 ${r[7]} 人。此为演示汇总，未接入患者明细。`);});
  if(window.StatisticsFilters){StatisticsFilters.mount(document.getElementById('dlFilters'),v=>{document.getElementById('dlScope').textContent='当前选择：'+[v.org||'全部机构',v.dept,v.team,v.person,v.disease].filter(Boolean).join(' / ');const msg=document.getElementById('dlMessage');msg.hidden=false;msg.textContent=`已选择 ${v.start} 至 ${v.end}；当前展示原图演示数据，筛选尚未接入业务数据。`;}, {orgs:{A机构:['心内科','内分泌科'],B机构:['全科','肾内科'],C机构:['全科']},people:[],diseases:['高血压','糖尿病','CKD','乳腺结节']},{start:'2026-07-01',end:'2026-07-31'},{variant:'operations',orgLabel:'全部机构',applyOnChange:false});}
  if(new URLSearchParams(location.search).get('view')==='dashboardLatest')showListView('dashboardLatest');
})();
