import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ConfigProvider,App,Alert,Checkbox,Divider,Input,Button,Tabs,Tree,Table,Avatar,Badge,Dropdown,Popover,Pagination,Modal,Form,Select,Drawer,Descriptions,Space,Empty,Tooltip,Upload} from 'antd';
import {SearchOutlined,PlusOutlined,LeftOutlined,RightOutlined,SettingOutlined,UploadOutlined,DownloadOutlined} from '@ant-design/icons';
import zhCN from 'antd/locale/zh_CN';
import {parseCsv,validatePersonnelImport,personnelTemplateCsv} from './personnel-import.mjs';
import {sourceRegions,sourceOrganizations} from './organization-source-data.mjs';
const departments=['医学美容科','儿科门诊','骨外一科门诊','疼痛科门诊','康复医学科门诊','骨外二科门诊','胸外科','风湿免疫科','眼科','心理科','口腔科','消化内科一病区','医学影像科','输血科','皮肤科','急诊医学科'];
const wards=['消化内科一病区','肾内科一病区','内分泌科一病区','骨外科一病区'];
const departmentTypes=[{key:'outpatient',label:'门诊',aliases:['outpatient','门诊','门诊科室']},{key:'inpatient',label:'住院',aliases:['inpatient','住院','住院科室']},{key:'medical',label:'医技',aliases:['medical','医技','医技科室']},{key:'other',label:'其他',aliases:['other','其他','其他科室']}];
const medicalDepartments=['医学影像科','输血科','药学部','检验科','病理科','超声科','放射科'];
const otherDepartments=['营养科'];
function departmentType(name='',sourceType=''){
 const normalizedType=String(sourceType||'');
 if(normalizedType.includes('门诊'))return'outpatient';
 if(normalizedType.includes('住院'))return'inpatient';
 if(normalizedType.includes('医技'))return'medical';
 if(normalizedType.includes('其他'))return'other';
 if(medicalDepartments.some(v=>name.includes(v)))return'medical';
 if(otherDepartments.some(v=>name.includes(v)))return'other';
 if(wards.includes(name)||name.includes('病区'))return'inpatient';
 return departmentTypes.find(v=>v.aliases.includes(sourceType))?.key||'other';
}
function departmentTypeLabel(type){return departmentTypes.find(v=>v.key===type)?.label||'其他'}
const organizationNames=['南宁市第二人民医院','南宁市第五人民医院','南宁市妇幼保健院','南宁中医医院','南宁第一人民医院','柳州市人民医院','桂林市人民医院'];
function readOrganizationData(){
 let data;
 try{
  const current=JSON.parse(localStorage.getItem('organization-management-v4'));
  const previous=JSON.parse(localStorage.getItem('organization-management-v2'));
  const old=JSON.parse(localStorage.getItem('organization-management-v1'));
  data=current?.orgs?.length?current:previous?.orgs?.length?previous:{orgs:Array.isArray(old)?old:null};
 }catch{}
 const savedOrganizations=Array.isArray(data?.orgs)?data.orgs:[];
 const savedRegions=Array.isArray(data?.regions)?data.regions:[];
 const organizationKey=item=>item?.code||item?.id||item?.name;
 const regionKey=item=>item?.code||item?.id||item?.name;
 const savedOrganizationMap=new Map(savedOrganizations.map(item=>[organizationKey(item),item]));
 const savedRegionMap=new Map(savedRegions.map(item=>[regionKey(item),item]));
 const orgs=[
  ...sourceOrganizations.map(item=>{
   const saved=savedOrganizationMap.get(organizationKey(item));
   return saved?{...item,...saved,departments:saved.departments?.length?saved.departments:item.departments}:item;
  }),
  ...savedOrganizations.filter(item=>!sourceOrganizations.some(source=>organizationKey(source)===organizationKey(item)))
 ];
 const regions=[
  ...sourceRegions.map(item=>({...item,...savedRegionMap.get(regionKey(item))})),
  ...savedRegions.filter(item=>!sourceRegions.some(source=>regionKey(source)===regionKey(item)))
 ];
 const availableOrganizations=orgs.length?orgs:organizationNames.map((name,i)=>({id:'org-'+i,name,departments:[]}));
 return {regions,orgs:availableOrganizations.map(o=>{
  const source=[...(o.id==='org-0'?[...departments.map(name=>({name,type:'门诊科室'})),...wards.map(name=>({name,type:'住院科室'})),...medicalDepartments.map(name=>({name,type:'医技科室'})),...otherDepartments.map(name=>({name,type:'其他科室'}))]:[]),...(o.departments||[])].map(d=>({...d,category:departmentType(d.name,d.category||d.type)}));
  return {...o,departments:source.filter((d,i,a)=>a.findIndex(x=>x.name===d.name&&x.category===d.category)===i)};
 })};
}
const ALL_SCOPE='__all__';
function readOrganizationScope(){try{const saved=JSON.parse(localStorage.getItem('global-organization-scope-v1'));return window.organizationScope||saved||{consortiums:[ALL_SCOPE],institutions:[ALL_SCOPE],allConsortiums:true,allInstitutions:true}}catch{return {consortiums:[ALL_SCOPE],institutions:[ALL_SCOPE],allConsortiums:true,allInstitutions:true}}}
function organizationsInScope(organizations,regions,scope){const consortiums=scope?.consortiums||[],institutions=scope?.institutions||[];const allConsortiums=scope?.allConsortiums??(!consortiums.length||consortiums.includes(ALL_SCOPE)),allInstitutions=scope?.allInstitutions??(!institutions.length||institutions.includes(ALL_SCOPE));const regionNames=new Set(allConsortiums?regions.map(item=>item.name):regions.filter(item=>consortiums.includes(item.code)||consortiums.includes(item.id)||consortiums.includes(item.name)).map(item=>item.name));return organizations.filter(item=>regionNames.has(item.region)&&(allInstitutions||institutions.includes(item.code)||institutions.includes(item.id)||institutions.includes(item.name)))}
function departmentOptions(orgs,id,type){return (orgs.find(o=>o.id===id)?.departments||[]).filter(d=>(d.category||departmentType(d.name,d.type))===type).map(d=>d.name)}
const titles=['主任医师','副主任医师','主治医师','住院医师','主任护师','副主任护师','主管护师','护师','护士','主任技师','副主任技师','主管技师','技师'];
const legacyDemoNames=['1','孙医生','黄医生','周医生','刘医生','赵医生','陈医生','张医生','王医生','李医生'];
const key='personnel-management-v1';
const demoKey='personnel-demo-seeded-v2';
const demoVersion='4';
const demoSurnames=['张','李','王','刘','陈','杨','黄','赵','周','吴','徐','孙','胡','朱','高','林','何','郭','马','罗','梁','宋','郑','谢','韩','唐'];
const demoGivenNames=['明轩','嘉怡','文浩','欣妍','梓涵','宇辰','思远','雅雯','俊熙','雨桐','子墨','诗涵','浩然','梦琪','博文','佳宁','泽宇','静怡','承泽','若彤','景行','舒雅','安然','语晨','清越','慕辰','晓彤','婉宁','志鹏','梦洁'];
const doctorTitles=['主任医师','副主任医师','主治医师','住院医师'];
const nurseTitles=['副主任护师','主管护师','护师','护士'];
const technicianTitles=['副主任技师','主管技师','技师'];
const ignoredDemoDepartments=/收费|办公室|财务|后勤|仓库|停车|挂号/;
let demoIndex=0;
const allDemoPersonnel=sourceOrganizations.flatMap((organization,organizationIndex)=>{
 const firstDepartmentByType=departmentTypes.map(({key:type})=>(organization.departments||[]).find(item=>departmentType(item.name,item.category||item.type)===type&&!ignoredDemoDepartments.test(item.name))).filter(Boolean);
 return firstDepartmentByType.flatMap((department,departmentIndex)=>Array.from({length:3},(_,staffIndex)=>{
  const index=demoIndex++;
  const type=departmentType(department.name,department.category||department.type);
  const role=type==='medical'?'医技人员':staffIndex===2?'护士':'医生';
  const title=role==='医技人员'?technicianTitles[(organizationIndex+departmentIndex+staffIndex)%technicianTitles.length]:role==='护士'?nurseTitles[(organizationIndex+departmentIndex)%nurseTitles.length]:doctorTitles[(organizationIndex+departmentIndex+staffIndex)%doctorTitles.length];
  const name=demoSurnames[index%demoSurnames.length]+demoGivenNames[Math.floor(index/demoSurnames.length)%demoGivenNames.length];
  const organizationCode=String(organization.code||organization.id).replace(/[^A-Za-z0-9]/g,'').toLowerCase();
  return {id:`real-demo-${String(index+1).padStart(3,'0')}`,name,account:`${organizationCode}.${String(index+1).padStart(3,'0')}`,phone:String(13810000000+index),organization:organization.id,departments:[type+'|'+department.name],type,department:department.name,role,title,enabled:index%29!==0,introduction:`现任${organization.name}${department.name}${role}，负责本科室日常诊疗、质量管理及患者健康教育。`,specialties:type==='medical'?`${department.name}检查、质量控制、报告审核`:type==='inpatient'?`${department.name}常见疾病诊疗、住院管理、出院随访`:`${department.name}常见疾病诊疗、慢病管理、健康咨询`};
 }));
});
function ensureAccounts(rows){return rows}
function readPersonnel(){try{const stored=JSON.parse(localStorage.getItem(key));const cleaned=Array.isArray(stored)?stored.filter(row=>row?.id&&typeof row.name==='string'&&!(/^staff-\d+$/.test(row.id)&&legacyDemoNames.includes(row.name))):[];if(localStorage.getItem(demoKey)!==demoVersion){const customRows=cleaned.filter(row=>!/^demo-staff-|^bulk-demo-|^real-demo-/.test(row.id));const merged=ensureAccounts([...customRows,...allDemoPersonnel]);localStorage.setItem(key,JSON.stringify(merged));localStorage.setItem(demoKey,demoVersion);return merged}const normalized=ensureAccounts(cleaned);if(!Array.isArray(stored)||normalized.some((row,index)=>row!==cleaned[index]))localStorage.setItem(key,JSON.stringify(normalized));return normalized}catch{return ensureAccounts(allDemoPersonnel)}}
const avatar='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><circle cx="20" cy="20" r="20" fill="#bdc3d2"/><path d="M8 40v-7q12-10 24 0v7" fill="#fafafa"/><path d="m16 29 4 4 4-4-4-3" fill="#edd4b0"/><path d="m18 33 2-2 2 2-1 7h-2" fill="#244ce1"/><ellipse cx="20" cy="18" rx="8" ry="10" fill="#fff0d4"/><path d="M12 19v-9q9-7 16 0v10l-2-7q-7 2-12-1z" fill="#17212b"/></svg>');
function normalizeMembership(value){const separator=value.indexOf('|');if(separator<0)return value;const type=value.slice(0,separator),name=value.slice(separator+1);return departmentType(name,type)+'|'+name}
function memberships(row){return (Array.isArray(row.departments)&&row.departments.length?row.departments:[row.type+'|'+row.department]).map(normalizeMembership).slice(0,1)}
function inDepartment(row,type,name){return memberships(row).includes(type+'|'+name)}
function inType(row,type){return memberships(row).some(v=>v.startsWith(type+'|'))}
function departmentText(row){return memberships(row).map(v=>v.slice(v.indexOf('|')+1)).join('、')}
function Page(){
 const {message,modal}=App.useApp();const [form]=Form.useForm();
 const [organizationData]=useState(readOrganizationData),organizations=organizationData.orgs,regions=organizationData.regions;
 const [scope,setScope]=useState(readOrganizationScope),scopedOrganizations=organizationsInScope(organizations,regions,scope);
 const [organization,setOrganization]=useState(()=>organizationsInScope(organizations,regions,readOrganizationScope())[0]?.id||organizations[0]?.id);const [expanded,setExpanded]=useState(()=>[]);
 const [rows,setRows]=useState(readPersonnel);
 const defaultColumns=['phone','status','department','title'];
 const [visibleColumns,setVisibleColumns]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('personnel-visible-columns-v1'));return Array.isArray(v)?v:defaultColumns}catch{return defaultColumns}});
 function changeVisibleColumns(values){setVisibleColumns(values);try{localStorage.setItem('personnel-visible-columns-v1',JSON.stringify(values))}catch{}}
 const [type,setType]=useState('outpatient'),[dept,setDept]=useState(departments[0]),[keyword,setKeyword]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(10),[collapsed,setCollapsed]=useState(false),[editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[saving,setSaving]=useState(false),[selected,setSelected]=useState([]);
 const [importDraft,setImportDraft]=useState(null),[importing,setImporting]=useState(false);
 const [personInput,setPersonInput]=useState(''),[personQuery,setPersonQuery]=useState('');
 useEffect(()=>{const sync=event=>setScope(event.detail||readOrganizationScope());window.addEventListener('organizationScopeChange',sync);return()=>window.removeEventListener('organizationScopeChange',sync)},[]);
 useEffect(()=>{setPersonInput('');setPersonQuery('')},[organization,type,dept]);
 const options=departmentOptions(organizations,organization,type);
 const organizationName=organizations.find(o=>o.id===organization)?.name||'';
 const query=keyword.trim().toLowerCase();
 const scopeKey=scopedOrganizations.map(item=>item.id).join('|');
 const rowOrganizationId=row=>organizations.some(item=>item.id===row.organization)?row.organization:row.organization==='org-0'?(organizations[0]?.id||row.organization):row.organization;
 useEffect(()=>{if(!scopedOrganizations.length){setOrganization('');setDept('');setExpanded([]);return}const activeOrganization=scopedOrganizations.find(item=>item.id===organization)||scopedOrganizations[0];const activeDepartments=departmentOptions(organizations,activeOrganization.id,type);if(activeOrganization.id!==organization)setOrganization(activeOrganization.id);if(!activeDepartments.includes(dept))setDept(activeDepartments[0]||'');const regionKeys=[...new Set(scopedOrganizations.map(item=>regions.find(region=>region.name===item.region)?.id).filter(Boolean))];setExpanded([...regionKeys,...scopedOrganizations.map(item=>item.id)])},[scopeKey,type]);
 useEffect(()=>{if(keyword.trim())setExpanded([...regions.map(item=>item.id),...scopedOrganizations.map(item=>item.id)])},[keyword,scopeKey]);
 const filtered=rows.filter(r=>rowOrganizationId(r)===organization&&inType(r,type)&&(query?(r.name.toLowerCase().includes(query)||departmentText(r).toLowerCase().includes(query)||(r.phone||'').includes(query)):inDepartment(r,type,dept))&&(!personQuery||r.name.toLowerCase().includes(personQuery)||(r.phone||'').includes(personQuery)));
 const actualPage=Math.min(page,Math.max(1,Math.ceil(filtered.length/size)));
 useEffect(()=>{setPage(1);setSelected([])},[organization,type,dept,keyword,personQuery]);
 function persist(next){try{localStorage.setItem(key,JSON.stringify(next));setRows(next);return true}catch{message.error('保存失败：浏览器存储不可用，请检查后重试');return false}}
 function openEditor(row){form.resetFields();const currentDepartment=row?memberships(row)[0]:(options.includes(dept)?type+'|'+dept:options[0]?type+'|'+options[0]:undefined);form.setFieldsValue(row?{...row,organization:rowOrganizationId(row),departmentSelection:currentDepartment}:{organization,departmentSelection:currentDepartment,enabled:true});setEditor(row||{});}
 function resetPassword(row){modal.info({title:'重置密码',content:<><p>医护：{row.name}</p><p>当前为本地预览，尚未接入账号服务，无法重置实际登录密码。</p></>,okText:'知道了'})}
 function confirmAction(row,action){const remove=action==='delete';modal.confirm({title:remove?'删除医护':row.enabled?'禁用医护':'启用医护',content:remove?`确定删除“${row.name}”吗？删除后无法恢复。`:row.enabled?`禁用“${row.name}”后，该医护将不可使用医护服务，资料仍会保留。`:`确定启用“${row.name}”吗？`,okText:remove?'删除':'确定',cancelText:'取消',okButtonProps:{danger:remove},onOk(){const next=remove?rows.filter(r=>r.id!==row.id):rows.map(r=>r.id===row.id?{...r,enabled:!r.enabled}:r);if(!persist(next))return Promise.reject();setDetail(null);message.success(remove?'医护已删除':row.enabled?'医护已禁用':'医护已启用')}})}
 async function save(){let values;try{values=await form.validateFields()}catch{return}setSaving(true);try{values={...values,name:values.name.trim(),account:String(values.account||'').trim(),phone:(values.phone||'').trim()};if(values.account&&rows.some(r=>r.id!==editor.id&&(r.account||'').toLowerCase()===values.account.toLowerCase())){form.setFields([{name:'account',errors:['该账号已被其他医护使用']}]);return}if(values.phone&&rows.some(r=>r.id!==editor.id&&r.phone===values.phone)){form.setFields([{name:'phone',errors:['该手机号已被其他医护使用']}]);return}const primary=values.departmentSelection;const row={...editor,...values,departments:[primary],type:primary.split('|')[0],department:primary.slice(primary.indexOf('|')+1),id:editor.id||'staff-'+crypto.randomUUID()};delete row.departmentSelection;delete row.remarks;const next=editor.id?rows.map(r=>r.id===editor.id?row:r):[...rows,row];if(persist(next)){setOrganization(row.organization);setType(row.type);setDept(row.department);setKeyword('');setPersonInput('');setPersonQuery('');setPage(editor.id?1:Math.ceil(next.filter(r=>rowOrganizationId(r)===row.organization&&inDepartment(r,row.type,row.department)).length/size));setEditor(null);setDetail(null);message.success(editor.id?'医护资料已更新':'医护添加成功')}}finally{setSaving(false)}}
 function batchDisable(){if(!selected.length)return;modal.confirm({title:'批量禁用医护',content:`确定禁用选中的 ${selected.length} 位医护吗？`,okText:'确定禁用',cancelText:'取消',onOk(){if(!persist(rows.map(r=>selected.includes(r.id)?{...r,enabled:false}:r)))return Promise.reject();setSelected([]);message.success('选中医护已禁用')}})}
 function downloadImportTemplate(){const currentOrg=organizations.find(o=>o.id===organization),currentDepartment={name:dept,type,label:departmentTypeLabel(type)};const blob=new Blob([personnelTemplateCsv(currentOrg,currentDepartment)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${currentOrg.name}-人员导入模板.csv`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);message.success('人员导入模板已下载')}
 async function readImportFile(file){setImporting(true);try{if(file.size>2*1024*1024)throw new Error('文件不能超过 2MB');const currentOrg=organizations.find(o=>o.id===organization);const orgDepartments=(currentOrg.departments||[]).map(item=>({name:item.name,type:item.category||departmentType(item.name,item.type)}));const result=validatePersonnelImport(parseCsv(await file.text()),{organization:currentOrg,departments:orgDepartments,existing:rows,titles});setImportDraft({name:file.name,...result});if(result.errors.length)message.error('文件校验未通过，请按提示修改');else message.success(`校验通过，共 ${result.staff.length} 位人员`)}catch(error){setImportDraft({name:file.name,staff:[],errors:[error.message||'文件读取失败']});message.error(error.message||'文件读取失败')}finally{setImporting(false)}return Upload.LIST_IGNORE}
 function confirmImport(){if(!importDraft?.staff?.length||importDraft.errors?.length)return;setImporting(true);try{const imported=importDraft.staff.map((row,index)=>({...row,id:'staff-'+crypto.randomUUID()+'-'+index}));if(!persist([...rows,...imported]))return;setImportDraft(null);setPage(1);message.success(`成功导入 ${imported.length} 位人员`)}finally{setImporting(false)}}
 const optionalColumns=[{key:'phone',title:'手机号',dataIndex:'phone',width:160,render:v=>v||'--'},{key:'status',title:'状态',width:110,render:(_,r)=><Badge status={r.enabled?'success':'default'} text={r.enabled?'正常':'禁用'}/>},{key:'department',title:'科室',width:230,render:(_,r)=><Tooltip title={departmentText(r)}><span>{departmentText(r)}</span></Tooltip>},{key:'role',title:'身份',dataIndex:'role',width:120,render:v=>v||'--'},{key:'title',title:'职称',dataIndex:'title',width:140,render:v=>v||'--'}];
 const columns=[{key:'name',title:'姓名',dataIndex:'name',width:220,render:name=><Space size={10}><Avatar size={32} src={avatar}/><span>{name}</span></Space>},...optionalColumns.filter(c=>visibleColumns.includes(c.key)),{key:'action',title:'操作',width:130,fixed:'right',render:(_,r)=><Space size={4}><Button type="link" onClick={()=>openEditor(r)}>编辑</Button><Dropdown trigger={['click']} menu={{items:[{key:'reset',label:'重置密码'},{key:'delete',label:'删除',danger:true}],onClick:({key:k})=>k==='reset'?resetPassword(r):confirmAction(r,k)}}><Button type="link" aria-label={r.name+'的更多操作'}>更多</Button></Dropdown></Space>}];
 const columnSettings=<div className="personnel-column-settings"><div className="personnel-column-settings-title">自定义列</div><Checkbox.Group value={visibleColumns} onChange={changeVisibleColumns}>{optionalColumns.map(c=><Checkbox key={c.key} value={c.key}>{c.title}</Checkbox>)}</Checkbox.Group><div className="personnel-column-settings-foot"><Button type="link" size="small" onClick={()=>changeVisibleColumns(defaultColumns)}>恢复默认</Button><span>姓名、操作固定显示</span></div></div>;
 const institutions=scope?.institutions||[];
 const allInstitutions=scope?.allInstitutions??(!institutions.length||institutions.includes(ALL_SCOPE));
 const departmentNodes=org=>{const names=departmentOptions(organizations,org.id,type);return names.map(name=>{const relatedPeople=rows.filter(row=>rowOrganizationId(row)===org.id&&inDepartment(row,type,name)).flatMap(row=>[row.name,row.phone||'']);return {key:org.id+'|'+type+'|'+name,title:name,isLeaf:true,organization:org.id,department:name,searchText:[name,...relatedPeople].join(' ').toLowerCase()}})};
 const scopedIds=new Set(scopedOrganizations.map(item=>item.id));
 const organizationNode=(org,preserveHierarchy)=>{const childOrganizations=preserveHierarchy?scopedOrganizations.filter(item=>(item.parentId||null)===org.id).map(item=>organizationNode(item,true)):[];const children=[...childOrganizations,...departmentNodes(org)];return {key:org.id,title:org.name,selectable:false,isLeaf:false,searchText:org.name.toLowerCase(),children:children.length?children:[{key:org.id+'|'+type+'|empty',title:`暂无${departmentTypeLabel(type)}科室`,selectable:false,disabled:true,isLeaf:true,searchText:''}]}};
 const directOrganizationNodes=items=>items.map(item=>organizationNode(item,false));
 const regionNode=(region,items,preserveHierarchy)=>{const roots=preserveHierarchy?items.filter(item=>!item.parentId||!scopedIds.has(item.parentId)).map(item=>organizationNode(item,true)):directOrganizationNodes(items);return {key:region.id,title:region.name,selectable:false,isLeaf:false,searchText:region.name.toLowerCase(),children:roots}};
 let personnelTreeData;
 if(scopedOrganizations.length===1&&!allInstitutions)personnelTreeData=directOrganizationNodes(scopedOrganizations);
 else{const selectedRegions=regions.filter(region=>scopedOrganizations.some(item=>item.region===region.name));personnelTreeData=selectedRegions.map(region=>regionNode(region,scopedOrganizations.filter(item=>item.region===region.name),allInstitutions));}
 const filterTree=nodes=>nodes.map(node=>{const children=node.children?filterTree(node.children):[];const matches=!query||node.searchText?.includes(query);return matches||children.length?{...node,...(node.children?{children}: {})}:null}).filter(Boolean);
 personnelTreeData=filterTree(personnelTreeData);
 return <div className={'personnel-shell'+(collapsed?' personnel-collapsed':'')}>
 <aside className="personnel-sidebar"><Input allowClear prefix={<SearchOutlined/>} placeholder="机构/科室/人员姓名" aria-label="搜索科室或医护" value={keyword} onChange={e=>setKeyword(e.target.value)}/><Tabs activeKey={type} items={departmentTypes.map(({key,label})=>({key,label}))} onChange={t=>{setType(t);setDept(departmentOptions(organizations,organization,t)[0]||'');setSelected([])}}/><div className="personnel-departments">{personnelTreeData.length?<Tree blockNode showLine={{showLeafIcon:false}} onExpand={setExpanded} expandedKeys={expanded} autoExpandParent selectedKeys={dept?[organization+'|'+type+'|'+dept]:[]} treeData={personnelTreeData} onSelect={(_,info)=>{if(!info.node.department)return;setOrganization(info.node.organization);setDept(info.node.department);setKeyword('')}}/>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="当前筛选范围暂无机构或科室"/>}</div></aside>
 <Tooltip title={collapsed?'展开科室':'收起科室'}><Button className="personnel-collapse" icon={collapsed?<RightOutlined/>:<LeftOutlined/>} aria-label={collapsed?'展开科室':'收起科室'} onClick={()=>setCollapsed(!collapsed)}/></Tooltip>
 <main className="personnel-content"><div className="personnel-heading"><h2>{query?'搜索结果':dept||'暂无科室'}</h2><span className="personnel-organization-name">{organizationName} · {departmentTypeLabel(type)}</span><span>医护人员数： {filtered.length}</span></div><div className="personnel-toolbar"><Input.Search className="personnel-staff-search" placeholder="人员名称 / 手机号" aria-label="查找人员名称或手机号" allowClear value={personInput} onChange={e=>{setPersonInput(e.target.value);if(!e.target.value)setPersonQuery('')}} onSearch={v=>setPersonQuery(v.trim().toLowerCase())}/><Popover placement="bottomLeft" trigger="click" content={columnSettings}><Tooltip title="自定义设置列"><Button icon={<SettingOutlined/>} aria-label="自定义设置列"/></Tooltip></Popover><Space className="personnel-toolbar-actions"><Button icon={<UploadOutlined/>} onClick={()=>setImportDraft({name:'',staff:[],errors:[]})}>导入人员</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>openEditor()}>添加医护</Button></Space></div><div className="personnel-table"><Table rowKey="id" columns={columns} dataSource={filtered.slice((actualPage-1)*size,actualPage*size)} pagination={false} tableLayout="fixed" locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={personQuery?'未找到匹配的医护':query?'未找到匹配的科室或医护':'暂无已录入的医护人员'}/>}} scroll={{x:850}}/></div><div className="personnel-pagination"><Pagination current={actualPage} pageSize={size} total={filtered.length} showTotal={n=>`共 ${n} 条`} showSizeChanger showQuickJumper pageSizeOptions={[10,20,50]} onChange={(p,s)=>{setPage(p);setSize(s)}}/></div></main>
 <Drawer rootClassName="personnel-editor personnel-form-drawer" title={editor?.id?'编辑医护':'添加医护'} open={editor!==null} onClose={()=>!saving&&setEditor(null)} size={560} destroyOnHidden footer={<Space style={{display:'flex',justifyContent:'flex-start'}}><Button disabled={saving} onClick={()=>setEditor(null)}>取消</Button><Button type="primary" loading={saving} onClick={save}>保存</Button></Space>}><Form form={form} layout="vertical" preserve={false}><Divider orientation="left">基本信息</Divider><Form.Item name="name" label="姓名" rules={[{required:true,whitespace:true,message:'请输入姓名'}]}><Input maxLength={30} placeholder="请输入姓名"/></Form.Item><Form.Item name="account" label="账号" extra="选填；填写后可用于登录，仅支持字母、数字、点、下划线和短横线" rules={[{validator:(_,value)=>!value||/^[A-Za-z0-9._-]{4,30}$/.test(value)?Promise.resolve():Promise.reject(new Error('请输入4至30位有效账号'))}]}><Input maxLength={30} autoComplete="off" placeholder="请输入登录账号（选填）"/></Form.Item><Form.Item name="phone" label="手机号" rules={[{required:true,message:'请输入手机号'},{pattern:/^1[3-9]\d{9}$/,message:'请输入正确的11位手机号'}]}><Input maxLength={11} placeholder="请输入手机号"/></Form.Item><Divider orientation="left">工作信息</Divider><Form.Item name="organization" label="所属机构" rules={[{required:true,message:'请选择所属机构'}]}><Select showSearch options={scopedOrganizations.map(o=>({value:o.id,label:o.name}))} onChange={()=>form.setFieldValue('departmentSelection',undefined)}/></Form.Item><Form.Item noStyle shouldUpdate={(a,b)=>a.organization!==b.organization}>{({getFieldValue})=><Form.Item name="departmentSelection" label="科室" rules={[{required:true,message:'请选择科室'}]}><Select showSearch placeholder="请选择科室" options={departmentTypes.map(({key,label})=>({label,options:departmentOptions(organizations,getFieldValue('organization'),key).map(v=>({value:key+'|'+v,label:v}))}))}/></Form.Item>}</Form.Item><Form.Item name="role" label="身份" rules={[{required:true,message:'请选择身份'}]}><Select placeholder="请选择身份" options={['医生','护士','医技人员'].map(v=>({value:v,label:v}))}/></Form.Item><Form.Item name="title" label="职称" rules={[{required:true,message:'请选择职称'}]}><Select placeholder="请选择职称" options={titles.map(v=>({value:v,label:v}))}/></Form.Item><Form.Item name="enabled" label="状态"><Select options={[{value:true,label:'正常'},{value:false,label:'禁用'}]}/></Form.Item><Form.Item name="introduction" label="简介"><Input.TextArea rows={3} maxLength={1000} showCount placeholder="请输入医护简介"/></Form.Item><Form.Item name="specialties" label="擅长"><Input.TextArea rows={3} maxLength={1000} showCount placeholder="请输入擅长的诊疗领域"/></Form.Item></Form></Drawer>
 <Drawer rootClassName="personnel-editor" title="医护详情" open={!!detail} onClose={()=>setDetail(null)} size={480} footer={detail&&<Space><Button type="primary" onClick={()=>openEditor(detail)}>编辑医护</Button><Button onClick={()=>confirmAction(detail,'status')}>{detail.enabled?'禁用医护':'启用医护'}</Button><Button danger onClick={()=>confirmAction(detail,'delete')}>删除医护</Button></Space>}><Space style={{marginBottom:24}}><Avatar src={avatar} size={48}/><strong>{detail?.name}</strong></Space><Descriptions column={1} items={['organization','account','phone','role','department','title','enabled'].map((v,i)=>({key:v,label:['所属机构','账号','手机号','身份','科室','职称','状态'][i],children:v==='department'?(detail?departmentText(detail):'--'):v==='organization'?(organizations.find(o=>o.id===rowOrganizationId(detail||{}))?.name||'--'):v==='enabled'?(detail?.enabled?'正常':'禁用'):detail?.[v]||'--'}))}/></Drawer>
 <Modal rootClassName="personnel-import-modal" title="导入人员" open={importDraft!==null} onCancel={()=>!importing&&setImportDraft(null)} onOk={confirmImport} okText="确认导入" cancelText="取消" confirmLoading={importing} okButtonProps={{disabled:importing||!importDraft?.staff?.length||!!importDraft?.errors?.length}} width={720} destroyOnHidden><Space orientation="vertical" size={16} style={{width:'100%'}}><Alert type="info" showIcon title={`导入到：${organizationName}`} description="支持 CSV 文件，最多1000位、2MB。请先下载模板填写；账号选填且填写后不可重复，手机号不可重复，机构、科室、身份、职称须与系统选项一致。校验失败时不会导入任何数据。"/><Space><Button icon={<DownloadOutlined/>} onClick={downloadImportTemplate}>下载模板</Button><Upload accept=".csv,text/csv" showUploadList={false} beforeUpload={readImportFile} disabled={importing}><Button icon={<UploadOutlined/>} loading={importing}>选择文件</Button></Upload></Space>{importDraft?.name&&<div>文件：{importDraft.name}</div>}{!!importDraft?.errors?.length&&<Alert type="error" showIcon title="请修正文件后重新选择，尚未导入任何数据" description={<div className="personnel-import-errors">{importDraft.errors.map((error,index)=><div key={index}>{error}</div>)}</div>}/>} {!!importDraft?.staff?.length&&!importDraft.errors?.length&&<><Alert type="success" showIcon title={`校验通过，共 ${importDraft.staff.length} 位人员`}/><Table size="small" rowKey={row=>row.account||row.phone} dataSource={importDraft.staff} columns={[{title:'姓名',dataIndex:'name'},{title:'账号',dataIndex:'account',render:value=>value||'--'},{title:'手机号',dataIndex:'phone'},{title:'科室',dataIndex:'department'},{title:'身份',dataIndex:'role'},{title:'状态',dataIndex:'enabled',render:value=>value?'正常':'禁用'}]} pagination={{pageSize:5,showSizeChanger:false}} scroll={{x:720}}/></>}</Space></Modal>
 </div>
}
let root;window.mountPersonnelPage=()=>{const host=document.getElementById('personnelManagementView');if(!host||root)return;root=createRoot(host);root.render(<ConfigProvider locale={zhCN} theme={{token:{motion:false,colorPrimary:'#263bff',colorSuccess:'#35ce69',colorText:'#606c83',colorTextHeading:'#26354d',colorBorder:'#eeeeef',borderRadius:4,controlHeight:40,fontSize:14},components:{Tree:{titleHeight:40,indentSize:16,nodeSelectedBg:'#eeefff',nodeSelectedColor:'#4652ff'},Table:{headerBg:'#f4f5f7',headerColor:'#4e5b71',headerSplitColor:'transparent',cellPaddingBlock:20,cellPaddingInline:10,borderColor:'#f3f3f5'},Menu:{itemHeight:48,itemSelectedBg:'#eeefff',itemSelectedColor:'#4652ff',itemMarginInline:0},Pagination:{itemActiveBg:'#263bff'},Tabs:{horizontalItemGutter:32}}}}><App><Page/></App></ConfigProvider>)};
