import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ConfigProvider,App,Divider,Input,Button,Tabs,Tree,Table,Avatar,Badge,Dropdown,Pagination,Modal,Form,Select,Drawer,Descriptions,Space,Empty,Tooltip} from 'antd';
import {SearchOutlined,PlusOutlined,LeftOutlined,RightOutlined,EllipsisOutlined,SettingOutlined} from '@ant-design/icons';
import zhCN from 'antd/locale/zh_CN';
const departments=['医学美容科','儿科门诊','骨外一科门诊','疼痛科门诊','康复医学科门诊','骨外二科门诊','胸外科','风湿免疫科','眼科','心理科','口腔科','消化内科一病区','医学影像科','输血科','皮肤科','急诊医学科'];
const wards=['消化内科一病区','肾内科一病区','内分泌科一病区','骨外科一病区'];
const organizationNames=['南宁市第二人民医院','南宁市第五人民医院','南宁市妇幼保健院','南宁中医医院','南宁第一人民医院','柳州市人民医院','桂林市人民医院'];
function readOrganizations(){let orgs;try{const data=JSON.parse(localStorage.getItem('organization-management-v2'));const old=JSON.parse(localStorage.getItem('organization-management-v1'));orgs=data?.orgs||old}catch{}if(!Array.isArray(orgs)||!orgs.length)orgs=organizationNames.map((name,i)=>({id:'org-'+i,name,departments:[]}));return orgs.map(o=>({...o,departments:[...(o.id==='org-0'?[...departments.map(name=>({name,type:'门诊科室'})),...wards.map(name=>({name,type:'住院科室'}))]:[]),...(o.departments||[])].filter((d,i,a)=>a.findIndex(x=>x.name===d.name&&x.type===d.type)===i)}))}
function departmentOptions(orgs,id,type){return (orgs.find(o=>o.id===id)?.departments||[]).filter(d=>d.type===(type==='inpatient'?'住院科室':'门诊科室')).map(d=>d.name)}
const titles=['主任医师','副主任医师','主治医师','住院医师','主任护师','副主任护师','主管护师','护师','护士'];
const seed=['1','孙医生','黄医生','周医生','刘医生','赵医生','陈医生','张医生','王医生','李医生'].map((name,i)=>({id:'staff-'+i,name,phone:i===0?'13345678901':'',department:departments[0],title:i===0?'副主任医师':'',enabled:true,role:'医生',type:'outpatient',remarks:''}));
const key='personnel-management-v1';
const avatar='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><circle cx="20" cy="20" r="20" fill="#bdc3d2"/><path d="M8 40v-7q12-10 24 0v7" fill="#fafafa"/><path d="m16 29 4 4 4-4-4-3" fill="#edd4b0"/><path d="m18 33 2-2 2 2-1 7h-2" fill="#244ce1"/><ellipse cx="20" cy="18" rx="8" ry="10" fill="#fff0d4"/><path d="M12 19v-9q9-7 16 0v10l-2-7q-7 2-12-1z" fill="#17212b"/></svg>');
function memberships(row){return Array.isArray(row.departments)&&row.departments.length?row.departments:[row.type+'|'+row.department]}
function inDepartment(row,type,name){return memberships(row).includes(type+'|'+name)}
function inType(row,type){return memberships(row).some(v=>v.startsWith(type+'|'))}
function departmentText(row){return memberships(row).map(v=>v.slice(v.indexOf('|')+1)).join('、')}
function Page(){
 const {message,modal}=App.useApp();const [form]=Form.useForm();
 const [organizations]=useState(readOrganizations);const [organization,setOrganization]=useState(()=>organizations[0].id);const [expanded,setExpanded]=useState(()=>[organizations[0].id]);
 const [rows,setRows]=useState(()=>{try{const stored=JSON.parse(localStorage.getItem(key));return Array.isArray(stored)&&stored.every(r=>r.id&&typeof r.name==='string')?stored:seed}catch{return seed}});
 const [type,setType]=useState('outpatient'),[dept,setDept]=useState(departments[0]),[keyword,setKeyword]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(10),[collapsed,setCollapsed]=useState(false),[editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[saving,setSaving]=useState(false),[selection,setSelection]=useState(false),[selected,setSelected]=useState([]);
 const [personInput,setPersonInput]=useState(''),[personQuery,setPersonQuery]=useState('');
 useEffect(()=>{setPersonInput('');setPersonQuery('')},[organization,type,dept]);
 const options=departmentOptions(organizations,organization,type);
 const organizationName=organizations.find(o=>o.id===organization)?.name||'';
 const query=keyword.trim().toLowerCase();
 useEffect(()=>{if(keyword.trim())setExpanded(organizations.map(o=>o.id))},[keyword,organizations]);
 const filtered=rows.filter(r=>(r.organization||'org-0')===organization&&inType(r,type)&&(query?(r.name.toLowerCase().includes(query)||departmentText(r).toLowerCase().includes(query)||r.phone.includes(query)):inDepartment(r,type,dept))&&(!personQuery||r.name.toLowerCase().includes(personQuery)||(r.phone||'').includes(personQuery)));
 const actualPage=Math.min(page,Math.max(1,Math.ceil(filtered.length/size)));
 useEffect(()=>{setPage(1);setSelected([])},[organization,type,dept,keyword,personQuery]);
 function persist(next){try{localStorage.setItem(key,JSON.stringify(next));setRows(next);return true}catch{message.error('保存失败：浏览器存储不可用，请检查后重试');return false}}
 function openEditor(row){form.resetFields();form.setFieldsValue(row?{...row,organization:row.organization||'org-0',departments:memberships(row)}:{organization,departments:options.includes(dept)?[type+'|'+dept]:[],enabled:true});setEditor(row||{});}
 function resetPassword(row){modal.info({title:'重置密码',content:<><p>医护：{row.name}</p><p>当前为本地预览，尚未接入账号服务，无法重置实际登录密码。</p></>,okText:'知道了'})}
 function confirmAction(row,action){const remove=action==='delete';modal.confirm({title:remove?'删除医护':row.enabled?'禁用医护':'启用医护',content:remove?`确定删除“${row.name}”吗？删除后无法恢复。`:row.enabled?`禁用“${row.name}”后，该医护将不可使用医护服务，资料仍会保留。`:`确定启用“${row.name}”吗？`,okText:remove?'删除':'确定',cancelText:'取消',okButtonProps:{danger:remove},onOk(){const next=remove?rows.filter(r=>r.id!==row.id):rows.map(r=>r.id===row.id?{...r,enabled:!r.enabled}:r);if(!persist(next))return Promise.reject();setDetail(null);message.success(remove?'医护已删除':row.enabled?'医护已禁用':'医护已启用')}})}
 async function save(){let values;try{values=await form.validateFields()}catch{return}setSaving(true);try{values={...values,name:values.name.trim(),phone:(values.phone||'').trim()};if(values.phone&&rows.some(r=>r.id!==editor.id&&r.phone===values.phone)){form.setFields([{name:'phone',errors:['该手机号已被其他医护使用']}]);return}const primary=values.departments.includes(type+'|'+dept)?type+'|'+dept:values.departments[0];const row={...editor,...values,type:primary.split('|')[0],department:primary.slice(primary.indexOf('|')+1),id:editor.id||'staff-'+crypto.randomUUID()};delete row.remarks;const next=editor.id?rows.map(r=>r.id===editor.id?row:r):[...rows,row];if(persist(next)){setOrganization(row.organization);setType(row.type);setDept(row.department);setKeyword('');setPersonInput('');setPersonQuery('');setPage(editor.id?1:Math.ceil(next.filter(r=>(r.organization||'org-0')===row.organization&&inDepartment(r,row.type,row.department)).length/size));setEditor(null);setDetail(null);message.success(editor.id?'医护资料已更新':'医护添加成功')}}finally{setSaving(false)}}
 function batchDisable(){if(!selected.length)return;modal.confirm({title:'批量禁用医护',content:`确定禁用选中的 ${selected.length} 位医护吗？`,okText:'确定禁用',cancelText:'取消',onOk(){if(!persist(rows.map(r=>selected.includes(r.id)?{...r,enabled:false}:r)))return Promise.reject();setSelected([]);message.success('选中医护已禁用')}})}
 const columns=[{title:'姓名',dataIndex:'name',width:'26.5%',render:name=><Space size={10}><Avatar size={32} src={avatar}/><span>{name}</span></Space>},{title:'手机号',dataIndex:'phone',width:'18%',render:v=>v||'--'},{title:'状态',width:'11.7%',render:(_,r)=><Badge status={r.enabled?'success':'default'} text={r.enabled?'正常':'禁用'}/>},{title:'科室',width:'19.8%',render:(_,r)=><Tooltip title={departmentText(r)}><span>{departmentText(r)}</span></Tooltip>},{title:'职称',dataIndex:'title',width:'11.7%',render:v=>v||'--'},{title:'操作',width:'12.3%',render:(_,r)=><Space size={4}><Button type="link" onClick={()=>openEditor(r)}>编辑</Button><Dropdown trigger={['click']} menu={{items:[{key:'reset',label:'重置密码'},{key:'delete',label:'删除',danger:true}],onClick:({key:k})=>k==='reset'?resetPassword(r):confirmAction(r,k)}}><Button type="link" aria-label={`${r.name}的更多操作`}>更多</Button></Dropdown></Space>}];
 return <div className={'personnel-shell'+(collapsed?' personnel-collapsed':'')}>
 <aside className="personnel-sidebar"><Input allowClear prefix={<SearchOutlined/>} placeholder="机构/科室/人员姓名" aria-label="搜索科室或医护" value={keyword} onChange={e=>setKeyword(e.target.value)}/><Tabs activeKey={type} items={[{key:'outpatient',label:'门诊'},{key:'inpatient',label:'住院'}]} onChange={t=>{setType(t);setDept(departmentOptions(organizations,organization,t)[0]||'');setSelected([])}}/><div className="personnel-departments"><Tree blockNode showLine={{showLeafIcon:false}} onExpand={setExpanded} expandedKeys={expanded} autoExpandParent selectedKeys={dept?[organization+'|'+type+'|'+dept]:[]} treeData={organizations.map(o=>({key:o.id,title:o.name,selectable:false,children:departmentOptions(organizations,o.id,type).filter(d=>!query||o.name.toLowerCase().includes(query)||d.toLowerCase().includes(query)||rows.some(r=>(r.organization||'org-0')===o.id&&inType(r,type)&&inDepartment(r,type,d)&&(r.name.toLowerCase().includes(query)||(r.phone||'').includes(query)))).map(d=>({key:o.id+'|'+type+'|'+d,title:d,isLeaf:true,organization:o.id,department:d}))})).filter(o=>!query||o.children.length).map(o=>({...o,isLeaf:false,children:o.children.length?o.children:[{key:o.key+'|'+type+'|empty',title:type==='outpatient'?'暂无门诊科室':'暂无住院科室',selectable:false,disabled:true,isLeaf:true}]}))} onSelect={(_,info)=>{if(!info.node.department)return;setOrganization(info.node.organization);setDept(info.node.department);setKeyword('')}}/></div></aside>
 <Tooltip title={collapsed?'展开科室':'收起科室'}><Button className="personnel-collapse" icon={collapsed?<RightOutlined/>:<LeftOutlined/>} aria-label={collapsed?'展开科室':'收起科室'} onClick={()=>setCollapsed(!collapsed)}/></Tooltip>
 <main className="personnel-content"><div className="personnel-heading"><h2>{query?'搜索结果':dept||'暂无科室'}</h2><span className="personnel-organization-name">{organizationName} · {type==='outpatient'?'门诊':'住院'}</span><span>医护人员数： {filtered.length}</span></div><div className="personnel-toolbar"><Input.Search className="personnel-staff-search" placeholder="人员名称 / 手机号" aria-label="查找人员名称或手机号" allowClear value={personInput} onChange={e=>{setPersonInput(e.target.value);if(!e.target.value)setPersonQuery('')}} onSearch={v=>setPersonQuery(v.trim().toLowerCase())}/><Tooltip title="批量管理"><Button icon={<SettingOutlined/>} aria-label="批量管理" onClick={()=>{setSelection(!selection);setSelected([])}}/></Tooltip>{selection&&<><Button disabled={!selected.length} onClick={batchDisable}>禁用选中医护</Button><Button type="text" onClick={()=>{setSelection(false);setSelected([])}}>取消批量管理</Button></>}<Button type="primary" icon={<PlusOutlined/>} onClick={()=>openEditor()}>添加医护</Button></div><div className="personnel-table"><Table rowKey="id" columns={columns} dataSource={filtered.slice((actualPage-1)*size,actualPage*size)} pagination={false} tableLayout="fixed" rowSelection={selection?{selectedRowKeys:selected,onChange:setSelected}:undefined} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={personQuery?'未找到匹配的医护':query?'未找到匹配的科室或医护':'本科室暂无医护'}/>}} scroll={{x:850}}/></div><div className="personnel-pagination"><Pagination current={actualPage} pageSize={size} total={filtered.length} showTotal={n=>`共 ${n} 条`} showSizeChanger pageSizeOptions={[10,20,50]} onChange={(p,s)=>{setPage(p);setSize(s)}}/></div></main>
 <Drawer rootClassName="personnel-editor personnel-form-drawer" title={editor?.id?'编辑医护':'添加医护'} open={editor!==null} onClose={()=>!saving&&setEditor(null)} size={560} destroyOnHidden footer={<Space style={{display:'flex',justifyContent:'flex-start'}}><Button disabled={saving} onClick={()=>setEditor(null)}>取消</Button><Button type="primary" loading={saving} onClick={save}>保存</Button></Space>}><Form form={form} layout="vertical" preserve={false}><Divider orientation="left">基本信息</Divider><Form.Item name="name" label="姓名" rules={[{required:true,whitespace:true,message:'请输入姓名'}]}><Input maxLength={30} placeholder="请输入姓名"/></Form.Item><Form.Item name="phone" label="手机号" rules={[{required:true,message:'请输入手机号'},{pattern:/^1[3-9]\d{9}$/,message:'请输入正确的11位手机号'}]}><Input maxLength={11} placeholder="请输入手机号"/></Form.Item><Divider orientation="left">工作信息</Divider><Form.Item name="organization" label="所属机构" rules={[{required:true,message:'请选择所属机构'}]}><Select showSearch options={organizations.map(o=>({value:o.id,label:o.name}))} onChange={()=>form.setFieldValue('departments',[])}/></Form.Item><Form.Item noStyle shouldUpdate={(a,b)=>a.organization!==b.organization}>{({getFieldValue})=><Form.Item name="departments" label="科室" rules={[{required:true,type:'array',min:1,message:'请至少选择一个科室'}]}><Select mode="multiple" allowClear showSearch placeholder="请选择科室（可多选）" options={['outpatient','inpatient'].map(t=>({label:t==='outpatient'?'门诊':'住院',options:departmentOptions(organizations,getFieldValue('organization'),t).map(v=>({value:t+'|'+v,label:v}))}))}/></Form.Item>}</Form.Item><Form.Item name="role" label="身份" rules={[{required:true,message:'请选择身份'}]}><Select placeholder="请选择身份" options={['医生','护士','医技人员'].map(v=>({value:v,label:v}))}/></Form.Item><Form.Item name="title" label="职称" rules={[{required:true,message:'请选择职称'}]}><Select placeholder="请选择职称" options={titles.map(v=>({value:v,label:v}))}/></Form.Item><Form.Item name="enabled" label="状态"><Select options={[{value:true,label:'正常'},{value:false,label:'禁用'}]}/></Form.Item><Form.Item name="introduction" label="简介"><Input.TextArea rows={3} maxLength={1000} showCount placeholder="请输入医护简介"/></Form.Item><Form.Item name="specialties" label="擅长"><Input.TextArea rows={3} maxLength={1000} showCount placeholder="请输入擅长的诊疗领域"/></Form.Item></Form></Drawer>
 <Drawer rootClassName="personnel-editor" title="医护详情" open={!!detail} onClose={()=>setDetail(null)} size={480} footer={detail&&<Space><Button type="primary" onClick={()=>openEditor(detail)}>编辑医护</Button><Button onClick={()=>confirmAction(detail,'status')}>{detail.enabled?'禁用医护':'启用医护'}</Button><Button danger onClick={()=>confirmAction(detail,'delete')}>删除医护</Button></Space>}><Space style={{marginBottom:24}}><Avatar src={avatar} size={48}/><strong>{detail?.name}</strong></Space><Descriptions column={1} items={['organization','phone','role','department','title','enabled'].map((v,i)=>({key:v,label:['所属机构','手机号','身份','科室','职称','状态'][i],children:v==='department'?(detail?departmentText(detail):'--'):v==='organization'?(organizations.find(o=>o.id===(detail?.organization||'org-0'))?.name||'--'):v==='enabled'?(detail?.enabled?'正常':'禁用'):detail?.[v]||'--'}))}/></Drawer>
 </div>
}
let root;window.mountPersonnelPage=()=>{const host=document.getElementById('personnelManagementView');if(!host||root)return;root=createRoot(host);root.render(<ConfigProvider locale={zhCN} theme={{token:{motion:false,colorPrimary:'#263bff',colorSuccess:'#35ce69',colorText:'#606c83',colorTextHeading:'#26354d',colorBorder:'#eeeeef',borderRadius:4,controlHeight:40,fontSize:14},components:{Tree:{titleHeight:40,indentSize:16,nodeSelectedBg:'#eeefff',nodeSelectedColor:'#4652ff'},Table:{headerBg:'#f4f5f7',headerColor:'#4e5b71',headerSplitColor:'transparent',cellPaddingBlock:20,cellPaddingInline:10,borderColor:'#f3f3f5'},Menu:{itemHeight:48,itemSelectedBg:'#eeefff',itemSelectedColor:'#4652ff',itemMarginInline:0},Pagination:{itemActiveBg:'#263bff'},Tabs:{horizontalItemGutter:32}}}}><App><Page/></App></ConfigProvider>)};
